---
- name: download etcd
  get_url: url={{etcd_tgz_url}} dest=/tmp/{{etcd_tgz}}
  
- name: unachive etcd
  unarchive: copy=no src='/tmp/{{etcd_tgz}}' dest='{{etcd_install_dir}}'

- name: link etcd and etcdctl
  file: >
    src='{{etcd_install_dir}}/{{etcd_name}}/{{item}}'
    dest='{{etcd_install_dir}}/{{item}}'
    state=link
    force=yes
  with_items:
    - etcd
    - etcdctl
